# Generated by Django 3.2.25 on 2026-09-30 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0015_problem_tag_governance'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=16)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=4)),
                ('source', models.CharField(default='manual', max_length=16)),
                ('confidence', models.DecimalField(decimal_places=3, default=1, max_digits=4)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_dependency',
            },
        ),
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('normalized_name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(default='')),
                ('category', models.CharField(max_length=32)),
                ('level', models.PositiveSmallIntegerField()),
                ('status', models.CharField(default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('aliases', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_point',
            },
        ),
        migrations.CreateModel(
            name='ProblemKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=16)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=4)),
                ('source', models.CharField(default='manual', max_length=16)),
                ('confidence', models.DecimalField(decimal_places=3, default=1, max_digits=4)),
                ('review_status', models.CharField(default='approved', max_length=16)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('knowledge_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge.knowledgepoint')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problem.problem')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'problem_knowledge',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeReviewEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=24)),
                ('object_key', models.CharField(max_length=64)),
                ('object_version', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=16)),
                ('reason', models.TextField(default='')),
                ('snapshot', models.JSONField()),
                ('request_id', models.CharField(db_index=True, max_length=64)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_review_event',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeMappingBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_version', models.PositiveIntegerField()),
                ('base_version', models.PositiveIntegerField(default=0)),
                ('approved_version', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('payload', models.JSONField()),
                ('reason', models.TextField(default='')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problem.problem')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_mapping_reviews', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_mapping_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_mapping_batch',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDependencyChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=16)),
                ('base_version', models.PositiveIntegerField(null=True)),
                ('relation_type', models.CharField(max_length=16, null=True)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('reason', models.TextField()),
                ('review_reason', models.TextField(default='')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('dependent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposed_dependents', to='knowledge.knowledgepoint')),
                ('prerequisite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposed_prerequisites', to='knowledge.knowledgepoint')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_dependency_reviews', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_dependency_submissions', to=settings.AUTH_USER_MODEL)),
                ('target_dependency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge.knowledgedependency')),
            ],
            options={
                'db_table': 'knowledge_dependency_change_request',
            },
        ),
        migrations.AddField(
            model_name='knowledgedependency',
            name='dependent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_dependencies', to='knowledge.knowledgepoint'),
        ),
        migrations.AddField(
            model_name='knowledgedependency',
            name='prerequisite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_dependencies', to='knowledge.knowledgepoint'),
        ),
        migrations.AddConstraint(
            model_name='problemknowledge',
            constraint=models.UniqueConstraint(fields=('problem', 'knowledge_point'), name='pk_problem_point_unique'),
        ),
        migrations.AddConstraint(
            model_name='problemknowledge',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'primary')), fields=('problem',), name='pk_one_primary'),
        ),
        migrations.AddConstraint(
            model_name='problemknowledge',
            constraint=models.CheckConstraint(check=models.Q(('weight__gt', 0), ('weight__lte', 1)), name='pk_weight_range'),
        ),
        migrations.AddConstraint(
            model_name='problemknowledge',
            constraint=models.CheckConstraint(check=models.Q(('review_status', 'approved')), name='pk_approved_only'),
        ),
        migrations.AddIndex(
            model_name='knowledgereviewevent',
            index=models.Index(fields=['object_type', 'object_key', 'object_version', 'created_time'], name='kre_object_history'),
        ),
        migrations.AddConstraint(
            model_name='knowledgepoint',
            constraint=models.CheckConstraint(check=models.Q(('level__gte', 1), ('level__lte', 5)), name='kp_level_1_5'),
        ),
        migrations.AddConstraint(
            model_name='knowledgepoint',
            constraint=models.CheckConstraint(check=models.Q(('version__gte', 1)), name='kp_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='knowledgemappingbatch',
            constraint=models.UniqueConstraint(fields=('problem', 'batch_version'), name='kmb_problem_batch_unique'),
        ),
        migrations.AddConstraint(
            model_name='knowledgemappingbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('problem',), name='kmb_one_pending'),
        ),
        migrations.AddConstraint(
            model_name='knowledgemappingbatch',
            constraint=models.CheckConstraint(check=models.Q(('reviewed_by__isnull', True), models.Q(('reviewed_by', django.db.models.expressions.F('submitted_by')), _negated=True), _connector='OR'), name='kmb_no_self_review'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedependencychangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('operation__in', ['update', 'delete']), ('status', 'pending')), fields=('target_dependency',), name='kd_one_pending_target'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedependencychangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('operation', 'create'), ('status', 'pending')), fields=('prerequisite', 'dependent'), name='kd_one_pending_create'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedependencychangerequest',
            constraint=models.CheckConstraint(check=models.Q(('weight__isnull', True), models.Q(('weight__gt', 0), ('weight__lte', 1)), _connector='OR'), name='kd_request_weight_range'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedependencychangerequest',
            constraint=models.CheckConstraint(check=models.Q(('reviewed_by__isnull', True), models.Q(('reviewed_by', django.db.models.expressions.F('submitted_by')), _negated=True), _connector='OR'), name='kd_no_self_review'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedependency',
            constraint=models.UniqueConstraint(fields=('prerequisite', 'dependent'), name='kd_directed_pair_unique'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedependency',
            constraint=models.CheckConstraint(check=models.Q(('prerequisite', django.db.models.expressions.F('dependent')), _negated=True), name='kd_no_self_loop'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedependency',
            constraint=models.CheckConstraint(check=models.Q(('weight__gt', 0), ('weight__lte', 1)), name='kd_weight_range'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedependency',
            constraint=models.CheckConstraint(check=models.Q(('version__gte', 1)), name='kd_version_positive'),
        ),
    ]
