# Generated by Django 2.1.7 on 2026-04-12 00:00

from django.db import migrations, models

try:
    from django.db.models import JSONField
except ImportError:
    from django.contrib.postgres.fields import JSONField


def clean_tag_name(name):
    if name is None:
        return ""
    return " ".join(str(name).strip().split())


def normalize_tag_name(name):
    cleaned_name = clean_tag_name(name)
    if not cleaned_name:
        return ""
    return cleaned_name.lower()


def forwards(apps, schema_editor):
    ProblemTag = apps.get_model("problem", "ProblemTag")
    for tag in ProblemTag.objects.all():
        tag.name = clean_tag_name(tag.name)
        tag.normalized_name = normalize_tag_name(tag.name)
        tag.aliases = []
        tag.save(update_fields=["name", "normalized_name", "aliases"])


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0014_problem_share_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemtag",
            name="aliases",
            field=JSONField(default=list),
        ),
        migrations.AddField(
            model_name="problemtag",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problemtag",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="problemtag",
            name="normalized_name",
            field=models.TextField(db_index=True, default=""),
        ),
        migrations.AddField(
            model_name="problemtag",
            name="rank",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]