# Generated by Django 2.1.7 on 2026-05-11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_participation_from_ranks(apps, schema_editor):
    ContestParticipation = apps.get_model('contest', 'ContestParticipation')
    ACMContestRank = apps.get_model('contest', 'ACMContestRank')
    OIContestRank = apps.get_model('contest', 'OIContestRank')

    batch = []
    for rank in ACMContestRank.objects.all().iterator():
        batch.append(ContestParticipation(
            user_id=rank.user_id,
            contest_id=rank.contest_id,
            has_submission=rank.submission_number > 0,
            submission_number=rank.submission_number,
            accepted_number=rank.accepted_number,
            total_score=0
        ))
    for rank in OIContestRank.objects.all().iterator():
        batch.append(ContestParticipation(
            user_id=rank.user_id,
            contest_id=rank.contest_id,
            has_submission=rank.submission_number > 0,
            submission_number=rank.submission_number,
            accepted_number=0,
            total_score=rank.total_score
        ))

    if batch:
        ContestParticipation.objects.bulk_create(batch)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0010_auto_20190326_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_enter_time', models.DateTimeField(auto_now_add=True)),
                ('last_enter_time', models.DateTimeField(auto_now=True)),
                ('enter_count', models.IntegerField(default=1)),
                ('has_submission', models.BooleanField(default=False)),
                ('submission_number', models.IntegerField(default=0)),
                ('accepted_number', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contest_participation',
                'ordering': ('-last_enter_time', '-id'),
                'index_together': {('user', 'last_enter_time')},
                'unique_together': {('user', 'contest')},
            },
        ),
        migrations.RunPython(backfill_participation_from_ranks, noop_reverse),
    ]
