# Generated by Django 2.1.7 on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_contestparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipation',
            name='calibrated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='is_calibrated',
            field=models.BooleanField(default=False),
        ),
    ]
